server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  
